// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Position, PositionData } from "./tables/Position.sol";
import { Metadata } from "./tables/Metadata.sol";
import { Count } from "./tables/Count.sol";
import { Bounds, BoundsData } from "./tables/Bounds.sol";
import { GameType } from "./tables/GameType.sol";
import { GameStatus } from "./tables/GameStatus.sol";
import { BuyIn } from "./tables/BuyIn.sol";
import { SubmissionWindow } from "./tables/SubmissionWindow.sol";
import { InviteExpiration } from "./tables/InviteExpiration.sol";
import { GameStartTime } from "./tables/GameStartTime.sol";
import { Player1 } from "./tables/Player1.sol";
import { Player2 } from "./tables/Player2.sol";
import { Player3 } from "./tables/Player3.sol";
import { Player4 } from "./tables/Player4.sol";
import { Player5 } from "./tables/Player5.sol";
import { Player6 } from "./tables/Player6.sol";
import { Player7 } from "./tables/Player7.sol";
import { Player8 } from "./tables/Player8.sol";
import { Player9 } from "./tables/Player9.sol";
import { Player10 } from "./tables/Player10.sol";
import { Player11 } from "./tables/Player11.sol";
import { Player12 } from "./tables/Player12.sol";
import { Solved } from "./tables/Solved.sol";
import { Balance } from "./tables/Balance.sol";
import { OtherPlayer } from "./tables/OtherPlayer.sol";
import { RematchCount } from "./tables/RematchCount.sol";
import { VoteRematch } from "./tables/VoteRematch.sol";
import { MessageTable } from "./tables/MessageTable.sol";
