// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Game } from "./../common.sol";

/**
 * @title IGameChainSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGameChainSystem {
  function games__newGame(
    Game gameType,
    uint32 submissionWindowSeconds,
    uint inviteExpirationTimestamp
  ) external payable;

  function games__joinGame(bytes32 gameId) external payable;

  function games__submitSolution(bytes32 gameId) external;

  function games__voteRematch(bytes32 gameId) external;

  function games__cancelPendingGame(bytes32 gameId) external;

  function games__claim(bytes32 gameId) external;
}
